// Generated by CoffeeScript 1.11.1
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  BSS.Condition_Element = (function(superClass) {
    extend(Condition_Element, superClass);

    function Condition_Element() {
      Condition_Element.__super__.constructor.call(this, new BSS.Condition_Model());
      this.buildFromConfiguration();
    }

    Condition_Element.prototype.buildFromConfiguration = function() {};

    return Condition_Element;

  })(BSS.Element);

}).call(this);
