// Generated by CoffeeScript 1.11.1
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  BSS.Junction_Element = (function(superClass) {
    extend(Junction_Element, superClass);

    function Junction_Element() {
      Junction_Element.__super__.constructor.call(this, new BSS.Junction_Model());
    }

    return Junction_Element;

  })(BSS.Element);

}).call(this);
