// Generated by CoffeeScript 1.11.1

/*
 * Testing Routines.
 *
 * Written by Bryce Summers
 */

(function() {
  EX.Testing = (function() {
    function Testing() {}

    return Testing;

  })();

}).call(this);
