// Generated by CoffeeScript 1.11.1

/*
    Written by Bryce Summers on 10.23.2017

    A model for the navigation of an object.

    This handles all of the logic for location and the creation of plans.
    Objects determine when to plan.
 */

(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  BSS.Navigation_Model = (function(superClass) {
    extend(Navigation_Model, superClass);

    function Navigation_Model() {
      this.current_location_model = null;
      this.destination = null;
      this.plan_stack = [];
      this.finished_plan_stack = [];
    }

    Navigation_Model.prototype.getCurrentLocation = function() {
      return this.current_location_model;
    };

    Navigation_Model.prototype.setCurrentLocation = function(path_model) {
      return this.current_location_model = path_model;
    };

    Navigation_Model.prototype.setDestination = function(path_model) {
      return this.destination = path_model;
    };

    Navigation_Model.prototype.updatePlan = function() {};

    return Navigation_Model;

  })(BSS.Model);

}).call(this);
