// Generated by CoffeeScript 1.11.1

/*
    Written by Bryce Summers on 10.23.2017

    A model for the statistics of an object.

    This is specific the agents within a particular game.
 */

(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  BSS.Statistics_Model = (function(superClass) {
    extend(Statistics_Model, superClass);

    function Statistics_Model() {
      this._food = 0;
      this._foodChanged = true;
      this.experiences = 0;
      this._narrative = "Press Up Key to begin journey!";
      this._narrativeChanged = true;
    }

    Statistics_Model.prototype.buildModel = function() {};


    /*
    Food.
     */

    Statistics_Model.prototype.foodChanged = function() {
      if (this._foodChanged) {
        this._foodChanged = false;
        return true;
      }
      return false;
    };

    Statistics_Model.prototype.getFood = function() {
      return this._food;
    };

    Statistics_Model.prototype.setFood = function(val) {
      this._food = val;
      return this._foodChanged = true;
    };


    /*
    Narration. Controls the text that represent's this agent's current inner narrative.
     */

    Statistics_Model.prototype.narrativeChanged = function() {
      if (this._narrativeChanged) {
        this._narrativeChanged = false;
        return true;
      }
      return false;
    };

    Statistics_Model.prototype.getNarrative = function() {
      return this._narrative;
    };

    Statistics_Model.prototype.setNarrative = function(val) {
      this._narrative = val;
      return this._narrativeChanged = true;
    };

    return Statistics_Model;

  })(BSS.Model);

}).call(this);
