// Generated by CoffeeScript 1.11.1

/*
    Written by Bryce Summers on 10.23.2017

    A model for the statistics of an object.

    This is specific the agents within a particular game.
 */

(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  BSS.Statistics_Model = (function(superClass) {
    extend(Statistics_Model, superClass);

    function Statistics_Model() {
      this._records = {};
      this._narrative = "Press the Up Key to begin journey!";
      this._narrativeChanged = true;
      this._narrativeType = "narrate";
      this._optionalNarrative = null;
      this._optionalNarrativeType = "narrate";
    }

    Statistics_Model.prototype.buildModel = function() {};


    /*
    Food.
     */

    Statistics_Model.prototype.foodChanged = function() {
      if (this._foodChanged) {
        this._foodChanged = false;
        return true;
      }
      return false;
    };

    Statistics_Model.prototype.getFood = function() {
      return this._food;
    };

    Statistics_Model.prototype.setFood = function(val) {
      this._food = val;
      return this._foodChanged = true;
    };


    /*
    Narration. Controls the text that represent's this agent's current inner narrative.
     */

    Statistics_Model.prototype.narrativeChanged = function() {
      if (this._narrativeChanged) {
        this._narrativeChanged = false;
        return true;
      }
      return false;
    };

    Statistics_Model.prototype.getNarrative = function() {
      return this._narrative;
    };

    Statistics_Model.prototype.setNarrative = function(val) {
      this._narrative = val;
      this._narrativeChanged = true;
    };

    Statistics_Model.prototype.setNarrativeType = function(type) {
      this._narrativeType = type;
    };

    Statistics_Model.prototype.getNarrativeType = function() {
      return this._narrativeType;
    };

    Statistics_Model.prototype.getOptionalNarrative = function(val) {
      var out;
      out = this._optionalNarrative;
      this._optionalNarrative = null;
      return out;
    };

    Statistics_Model.prototype.setOptionalNarrative = function(val) {
      this._optionalNarrative = val;
    };

    Statistics_Model.prototype.getOptionalNarrativeType = function() {
      return _optionalNarrativeType;
    };

    Statistics_Model.prototype.setOptionalNarrativeType = function(val) {
      var _optionalNarrativeType;
      _optionalNarrativeType = val;
    };

    Statistics_Model.prototype.hasOptionalNarrative = function() {
      return this._optionalNarrative !== null;
    };

    Statistics_Model.prototype.forgetOptionalNarrative = function() {
      return this._optionalNarrative = null;
    };

    Statistics_Model.prototype.getValue = function(name) {
      var val;
      val = this._records[name];
      if (val === void 0) {
        this._records[name] = 0;
        val = 0;
      }
      return val;
    };

    Statistics_Model.prototype.setValue = function(name, val) {
      return this._records[name] = val;
    };

    return Statistics_Model;

  })(BSS.Model);

}).call(this);
