// Generated by CoffeeScript 1.11.1
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  EX.I_All_Main = (function(superClass) {
    extend(I_All_Main, superClass);

    function I_All_Main(scene, camera) {
      this.scene = scene;
      this.camera = camera;
      I_All_Main.__super__.constructor.call(this);
      this._keyboard_input = new EX.I_Keyboard_Main(this.scene, this.camera);
      this.add_keyboard_input_controller(this._keyboard_input);
      this._time_input = new EX.I_Time_Main(this.scene, this.camera);
      this.add_time_input_controller(this._time_input);
    }

    I_All_Main.prototype.getMouseController = function() {
      return this._mouse_input;
    };

    return I_All_Main;

  })(BDS.Controller_Group);

}).call(this);
