// Generated by CoffeeScript 1.11.1
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  EX.I_Keyboard_Main = (function(superClass) {
    extend(I_Keyboard_Main, superClass);

    function I_Keyboard_Main(scene, camera) {
      var controlPlayer;
      this.scene = scene;
      this.camera = camera;
      I_Keyboard_Main.__super__.constructor.call(this);
      controlPlayer = new EX.Keyboard_ControlPlayer(this.scene, this.camera);
      this.add_keyboard_input_controller(controlPlayer);
      controlPlayer.setActive(true);
      this.state = "idle";
    }


    /* Get Controllers. */

    I_Keyboard_Main.prototype.deactivateTools = function() {

      /*
      @road_build_controller.setActive(false)
      @road_build_controller.cancel()
      @road_build_controller.finish()
       */
    };


    /*------------------------------------
      Internal Helper Functions.
    #--------------------------------------
     */


    /* Override global functionality, still passes commands to subtools. */


    /*
    key_down: (event) ->
    
        super(event)
     */

    return I_Keyboard_Main;

  })(BDS.Controller_Group);

}).call(this);
