// Generated by CoffeeScript 1.11.1
(function() {
  EX.I_Keyboard_Interface = (function() {
    function I_Keyboard_Interface(scene, camera) {
      this.scene = scene;
      this.camera = camera;
    }

    I_Keyboard_Interface.prototype.key_down = function(event) {};

    I_Keyboard_Interface.prototype.key_up = function(event) {};

    I_Keyboard_Interface.prototype.time = function(dt) {};

    I_Keyboard_Interface.prototype.isIdle = function() {};

    I_Keyboard_Interface.prototype.finish = function() {};

    return I_Keyboard_Interface;

  })();

}).call(this);
