// Generated by CoffeeScript 1.11.1
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  EX.I_Mouse_Main = (function(superClass) {
    extend(I_Mouse_Main, superClass);

    function I_Mouse_Main(scene, camera) {
      this.scene = scene;
      this.camera = camera;
      I_Mouse_Main.__super__.constructor.call(this);

      /*
      @ui_controller = new EX.UI_Controller(@scene, @camera)
      @add_mouse_input_controller(@ui_controller)
       */
      this.state = "idle";
    }


    /* Get Controllers. */

    I_Mouse_Main.prototype.deactivateTools = function() {

      /*
      @road_build_controller.setActive(false)
      @road_build_controller.cancel()
      @road_build_controller.finish()
       */
    };


    /*------------------------------------
      Internal Helper Functions.
    #--------------------------------------
     */

    I_Mouse_Main.prototype._create_cursor = function() {
      var h, mesh, mesh_factory, overlays, params, scale, w;
      mesh_factory = new EX.Unit_Meshes();
      params = {
        color: EX.style.cursor_circle_color
      };
      mesh = mesh_factory.newCircle(params);
      scale = EX.style.cursor_circle_radius;
      mesh.position.z = EX.style.cursor_circle_z;
      w = scale;
      h = scale;
      scale = mesh.scale;
      scale.x = w;
      scale.y = h;
      overlays = this.scene.getOverlays();
      overlays.addPermanentVisual(mesh);
      return this.pointer = mesh;
    };

    I_Mouse_Main.prototype.mouse_move = function(event) {
      var pos;
      I_Mouse_Main.__super__.mouse_move.call(this, event);
      pos = this.pointer.position;
      pos.x = event.x;
      return pos.y = event.y;
    };

    return I_Mouse_Main;

  })(BDS.Controller_Group);

}).call(this);
