// Generated by CoffeeScript 1.11.1
(function() {
  EX.I_Time_Interface = (function() {
    function I_Time_Interface(scene, camera) {
      this.scene = scene;
      this.camera = camera;
    }

    I_Time_Interface.prototype.time = function(dt) {};

    I_Time_Interface.prototype.isIdle = function() {};

    I_Time_Interface.prototype.finish = function() {};

    return I_Time_Interface;

  })();

}).call(this);
