// Generated by CoffeeScript 1.11.1

/*

Time Input Controller.

Written by Bryce Summmers on 1 - 31 - 2017.
 */

(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  EX.I_Time_Main = (function(superClass) {
    extend(I_Time_Main, superClass);

    function I_Time_Main(scene, camera) {
      var cameraFollowsAgent, sceneTimer, updateUIFromFocusAgent;
      this.scene = scene;
      this.camera = camera;
      I_Time_Main.__super__.constructor.call(this);
      cameraFollowsAgent = new EX.TimeTool_CameraFollowsAgent(this.scene, this.camera);
      this.add_time_input_controller(cameraFollowsAgent);
      cameraFollowsAgent.setActive(true);
      sceneTimer = new EX.TimeTool_SceneTimer(this.scene, this.camera);
      this.add_time_input_controller(sceneTimer);
      sceneTimer.setActive(true);
      updateUIFromFocusAgent = new EX.TimeTool_DisplayFocusAgentStatistics(this.scene, this.camera);
      this.add_time_input_controller(updateUIFromFocusAgent);
      updateUIFromFocusAgent.setActive(true);
    }

    return I_Time_Main;

  })(BDS.Controller_Group);

}).call(this);
