// Generated by CoffeeScript 1.11.1

/*
Auditory Rerpresentation.

Written by Bryce Summers.

Handles representation and plaback of audio clips and synthesis.
 */

(function() {
  BSS.Audio_Representation = (function() {
    function Audio_Representation() {}

    return Audio_Representation;

  })();

}).call(this);
