// Generated by CoffeeScript 1.11.1

/*
 *
 * Collision Representation Class.
 *
 * Written by Bryce Summers on 10.23.2017
 *
 * Represents a node in a collision geometry hiearchy, 
 * handles the management of a BVH and cooresponding areas.
 *
 * Usage: Configure, Build, Query.
 *
 */

(function() {
  BSS.Collision_Representation = (function() {
    function Collision_Representation() {
      this._bvh = new BDS.BVH2D();
      this._bounding_area = null;
    }


    /*
    
    Configuration.
     */

    Collision_Representation.prototype.addCollisionAreas = function(areas) {
      var anArea, i, len, results;
      results = [];
      for (i = 0, len = areas.length; i < len; i++) {
        anArea = areas[i];
        results.push(this.addCollisionArea(anArea));
      }
      return results;
    };

    Collision_Representation.prototype.addCollisionArea = function(area) {
      return this._bvh.add(area);
    };

    Collision_Representation.prototype.removeCollisionAreas = function(areas) {
      var anArea, i, len, results;
      results = [];
      for (i = 0, len = areas.length; i < len; i++) {
        anArea = areas[i];
        results.push(this.removeCollisionArea(anArea));
      }
      return results;
    };

    Collision_Representation.prototype.removeCollisionarea = function(area) {
      return this._bvh.remove(area);
    };


    /*
    
    Build
     */

    Collision_Representation.prototype.build = function() {
      return this.buildBoundingArea();
    };

    Collision_Representation.prototype.buildBoundingArea = function() {
      this._collision_area = this._bvh.toBoundingBox().toPolyline();
      this._collision_area.setAssociatedData(this);
      return this._collision_area;
    };


    /*
    
    Query.
     */

    Collision_Representation.prototype.getBoundingArea = function() {
      if (this._collision_area === null) {
        this.generateCollisionArea();
      }
      return this._collision_area;
    };

    Collision_Representation.prototype.containsPt = function(pt) {
      return this._bvh.query_point(pt) !== null;
    };

    return Collision_Representation;

  })();

}).call(this);
