// Generated by CoffeeScript 1.11.1

/*
Written by Bryce Summers on Mar.21.2018
Updates the scene's ui based on the statistics of the focus agent.
 */

(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  EX.TimeTool_DisplayFocusAgentStatistics = (function(superClass) {
    extend(TimeTool_DisplayFocusAgentStatistics, superClass);

    function TimeTool_DisplayFocusAgentStatistics(scene, camera) {
      this.scene = scene;
      this.camera = camera;
    }

    TimeTool_DisplayFocusAgentStatistics.prototype.time = function(dt) {
      var focus_agent, foodbox, ref, statistics, textbox, ui, ui_elements;
      focus_agent = this.scene.getFocusAgent();
      if (focus_agent === null) {
        return;
      }
      ref = this.scene.getUI(), ui = ref[0], ui_elements = ref[1];
      statistics = focus_agent.getModel().getStatistics();
      if (statistics.foodChanged()) {
        foodbox = ui_elements.foodbox;
        foodbox.str = EX.style.resource_name_food + statistics.getFood();
        ui.updateLabel(foodbox, {
          update_str: true
        });
      }
      if (statistics.narrativeChanged()) {
        textbox = ui_elements.textbox;
        textbox.str = EX.style.resource_name_food + statistics.getNarrative();
        return ui.updateLabel(textbox, {
          update_str: true
        });
      }
    };

    TimeTool_DisplayFocusAgentStatistics.prototype.isIdle = function() {
      return true;
    };

    TimeTool_DisplayFocusAgentStatistics.prototype.finish = function() {};

    return TimeTool_DisplayFocusAgentStatistics;

  })(EX.I_Tool_Controller);

}).call(this);
