// Generated by CoffeeScript 1.11.1

/*
Written by Bryce Summers on Mar.21.2018
Has the camera follow an agent.
 */

(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  EX.TimeTool_CameraFollowsAgent = (function(superClass) {
    extend(TimeTool_CameraFollowsAgent, superClass);

    function TimeTool_CameraFollowsAgent(scene, camera) {
      this.scene = scene;
      this.camera = camera;
    }

    TimeTool_CameraFollowsAgent.prototype.time = function(dt) {
      var agent, agent_model, camera_model, place, place_model, ref, target_loc, target_up;
      agent = this.scene.getFocusAgent();
      place = this.scene.getFocusPlace();
      if (agent === null || place === null) {
        return;
      }
      agent_model = agent.getModel();
      place_model = place.getModel();
      camera_model = place_model.getCamera();
      if (camera_model === null) {
        return;
      }
      ref = agent_model.getCurrentLocationAndHeading(), target_loc = ref[0], target_up = ref[1];
      camera_model.setCenter(target_loc);
      camera_model.setUpDirection(target_up);
      return camera_model.applyInverseToObj(this.scene.getView(), this.camera);
    };

    TimeTool_CameraFollowsAgent.prototype.isIdle = function() {
      return true;
    };

    TimeTool_CameraFollowsAgent.prototype.finish = function() {};

    return TimeTool_CameraFollowsAgent;

  })(EX.I_Tool_Controller);

}).call(this);
