// Generated by CoffeeScript 1.11.1

/*

Story loader class.
 */

(function() {
  BSS.Story_Loader = (function() {
    function Story_Loader() {}

    Story_Loader.prototype.load_story = function(file_name) {};

    Story_Loader.prototype.readFile = function(file_name) {};

    return Story_Loader;

  })();

}).call(this);
